@startuml Cas d’utilisation
left to right direction
actor Client
actor Commercial

usecase "Consulter le catalogue" as catalogue
usecase "Ajouter / Modifier le panier" as panier
usecase "S'inscrire / Se connecter" as connect
usecase "Créer une commande" as cre_com
usecase "Consulter ses commandes" as cons_com
usecase "Saisir les adresses de livraison / facturation" as info_liv_fac
usecase "Payer la commande" as payer
usecase "Transmettre la commande (client pro)" as com_pro
usecase "Appliquer le coefficient client" as coef
usecase "Valider la commande" as val_com
usecase "Générer facture et bon de commande" as gen_fac
usecase "Préparer / Expédier la commande" as pre_exp_com

Client --> catalogue
Client --> panier
Client --> connect
Client --> cre_com
Client --> cons_com
Client --> info_liv_fac
Client --> payer
Client --> com_pro

Commercial --> coef
Commercial --> val_com
Commercial --> pre_exp_com

cre_com --> gen_fac

@enduml
