@startuml Diagramme de séquence

actor Client
participant "Site" as Site
actor Commercial

Client -> Site: Accède au site
Site --> Client: Renvoie la liste des catégories / sous-catégories / produits

Client -> Site: Ajoute un produit à son panier
Site --> Client: Notification d'ajout

Client -> Site: Consulte son panier
Site --> Client: Renvoie la liste des articles et quantités

Client -> Site: Clique sur "Commander"

alt Le client n'est pas connecté
    Site --> Client: Redirection vers la page de connexion
    Client -> Site: Rentre ses identifiants / Crée un compte
    Site --> Client: Confirmation de connexion
end

Client -> Site: Renseigne / Valide ses informations de livraison et de facturation
Site -> Client: Notification d'enregistrement des informations
Client -> Site: Clique sur "Commander"

alt Le client est un professionnel 
    Site -> Commercial: La commande est transmise à un commercial
    Commercial -> Site: Applique le coefficient du client sur la commande
    Commercial -> Site: Valide la commande

else Le client est un particulier 
    Site -> Client: Demande le moyen de paiement
    Client -> Site: Choisit et entre ses informations de paiement
    Site -> Site: Vérifie les informations

    alt Le paiement est invalide
        Site --> Client: Affiche une erreur et demande de réessayer
    end
end

Site -> Site: Génère la facture
Site -> Client: La facture est envoyée au client
Site -> Commercial: Envoie les informations de la commande
Commercial -> Commercial: Prépare et envoie la commande
Commercial -> Site: Met à jour les informations de la commande
Site -> Site: Génère un bon de commande
Site -> Client: Le bon de commande est envoyé au client
Site -> Client: Le client est notifié de l'état de sa commande 

@enduml
