nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["https://localhost:5173", "http://localhost:5173"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
